### ISSUE TITLE
Crashes unexpectedly on a Commodore 64

### ISSUE THREAD

**Issue by matt-newcomer** [Skytlz/EpicBot#2]
Title. When running the bot, the python interpreter unexpectedly quits.

**Comment by Skytlz** [comment]
Dont run python 3.7 on a commodore 64 please

**Comment by memerson12** [comment]
What about Python 3.9? Can I run that version?

**Comment by Skytlz** [comment]
if you REALLY want to use a commodore 64 i'd recommend you heavily reconsider
